name: IOT DEVICE ANDROID RELEASE CI

on:
  release:
    types: [published]

env:
  IOT_SONATYPE_USERNAME: ${{ secrets.IOT_SONATYPE_USERNAME }}
  IOT_SONATYPE_PASSWORD: ${{ secrets.IOT_SONATYPE_PASSWORD }}
  GPG_DECRYPT_PASSPHRASE: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
  IOT_GPG_KEYNAME: ${{ secrets.IOT_GPG_KEYNAME }}
  IOT_GPG_PASSPHRASE: ${{ secrets.IOT_GPG_PASSPHRASE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          rm -rf hub/hub-android-demo/app-config.json explorer/device-android-demo/app-config.json hub/hub-device-java/src/test/unit_test_config.json explorer/explorer-device-java/src/test/unit_test_config.json
          gpg -d --passphrase "$GPG_DECRYPT_PASSPHRASE" --batch --quiet .github/hub-device-android/app-config.json.asc > hub/hub-android-demo/app-config.json
          gpg -d --passphrase "$GPG_DECRYPT_PASSPHRASE" --batch --quiet .github/explorer-device-android/app-config.json.asc > explorer/device-android-demo/app-config.json
          gpg -d --passphrase "$GPG_DECRYPT_PASSPHRASE" --batch --quiet .github/hub-device-java/unit_test_config.json.asc > hub/hub-device-java/src/test/unit_test_config.json
          gpg -d --passphrase "$GPG_DECRYPT_PASSPHRASE" --batch --quiet .github/explorer-device-java/unit_test_config.json.asc > explorer/explorer-device-java/src/test/unit_test_config.json
          gpg -d --passphrase "$GPG_DECRYPT_PASSPHRASE" --batch --quiet .github/sdk/secring.gpg.asc > secring.gpg
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install fir
        run: sudo gem install fir-cli

      - name: Fix SDKs Version
        run: |
          rtt=$(git describe --tags `git rev-list --tags --max-count=1`)
          rt=${rtt#*v}
          rc=$(git rev-parse --short HEAD)
          sed -i 's#def version.*#def version = \"'$rt'\"#g' config.gradle
      - name: Update Values of Signing
        run: |
          export KEY_ID_OF_SIGN=$IOT_GPG_KEYNAME
          export PASSWORD_OF_SIGN=$IOT_GPG_PASSPHRASE
          sh .github/scripts/updateValuesForSign.sh
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish aar and jar to Maven
        run: ./gradlew publish
      - name: Archive the apks
        uses: actions/upload-artifact@v2
        with:
          path: |
            'explorer/device-android-demo/build/outputs/apk/debug/*.apk'
            'hub/hub-android-demo/build/outputs/apk/debug/*.apk'
      - name: Upload apks to fir
        run: |
          expApk=$(ls explorer/device-android-demo/build/outputs/apk/release/*.apk)
          hubApk=$(ls hub/hub-android-demo/build/outputs/apk/release/*.apk)
          
          fir publish $expApk -T $IOT_FIRIM_API_TOKEN --oversea_turbo --force_pin_history
          fir publish $hubApk -T $IOT_FIRIM_API_TOKEN --oversea_turbo --force_pin_history
        env:
          IOT_FIRIM_API_TOKEN: ${{ secrets.IOT_FIRIM_API_TOKEN }}
